### ISSUE TITLE
Add easy way to fix Emergency case

### ISSUE THREAD

**Issue by WanderMax** [d3m3vilurr/vita-savemgr#21]
Any plan to add easy fix to emergency case? Like square to fix these failed case?
Thanks.

**Comment by d3m3vilurr** [comment]
it's little complicate.
sometimes can overwrite wrong data on recovery process.
many cases, just need to restart save manager, it will start auto cleanup, and fix problems.

so feature of manual fix button have low priority :)
can you share any broken scenario?

**Comment by WanderMax** [comment]
I think you can do like this:
For failed case in recovery process, when get TITLEID after user operation:
1. Search ux0:app/{TITLE_ID}, list eboot.bin.orig file on the to-do list if exist --> case 1;
2. Search ux0:app/{TITLE_ID}, list {TITLE_ID}_orig folder on the to-do list if exist --> case 2;
3. Search ux0:data/savemgr/tmp, list files on the to-do list if exist --> case 3;
4. List predefined methods as below and set one key to execute all (Warn users to do manual fix here):
     --> Remove eboot.bin and rename eboot.bin.orig to eboot.bin, if case 1 ;
     --> Remove {TITLE_ID} directory and rename {TITLE_ID}_orig to {TITLE_ID} , if case 2;
     --> Remove ux0:data/savemgr/tmp, if case 3;
5. List operation result, then exit
I don't know that case for cartridge game, you can check whether it can work.
Thanks.

**Comment by d3m3vilurr** [comment]
actually, dumper mode(injector launched this) cannot handle anythings.
cannot overwrite running process's eboot.bin. so we cannot assign square for this.

injector mode(app) exist check `tmp` file at start time, then auto cleanup ; so we don't need to handle this file.

if you want to all older files recover at start time, it make program too slow; i want avoid this.

real problem is ` can check validation of data`
i guess, it's very hard as sometimes.
so basically, i want this role should move to user's choice :)

for example, older savemgr can make this
```
ux0:patch/xxxx/eboot.bin
       patch.orig/xxxx/eboot.bin // <- but this is also savemgr
```

now a days, only some edge cases can break process;
1. force close then menually remove `tmp`.
2. force close then import games via CMA

so, i'll not make this complex feature before someone figure out another broken scenario of current version.
but patches are always welcome ;)

i guess real solution is `blocking to press PS button`, but i don't know yet how can do.

**Comment by WanderMax** [comment]
I don't know whether I describe it clearly. I mean that to do fix work in one new manger launch, not in the inject process. However it is all based on the guess that Save Manager can delete and rename in this condition like manual fix in VitaShell. I hope you can get my ideas. Thanks

**Comment by WanderMax** [comment]
@d3m3vilurr As I am not the programmer, so I can just share my thought.

**Comment by d3m3vilurr** [comment]
no more needs emergency steps
