### ISSUE TITLE
Error C2-12828-1

### ISSUE THREAD

**Issue by Mapachillo** [d3m3vilurr/vita-savemgr#58]
I tried to restore a save file that I made with version .80 and keeps showing this error message. I tried with version 1.0.0 and 2.0.0 Beta and it still didn't restore.

Also, I re-installed version 0.8.0 and now that shows the same error again.

I have a PS vita version 3.65 (enso)

**Comment by d3m3vilurr** [comment]
1. <= 1.0.0 not support 3.65
2. what happens in 2.0.0? not print any popup?

**Comment by Mapachillo** [comment]
Hello, thank you for the reply. I also tried 2.0.0 and the same error comes up.

**Comment by d3m3vilurr** [comment]
can you upload crash dump?

**Comment by sechstte** [comment]
Since the guy doesn't delivers and I have the same issue, I'll upload my crash dump (or what I think you mean by that since I've never done this before). I've tried on Disgaea 4 and Va11-Hall A, each one twice.


[logsiguess.zip](https://github.com/d3m3vilurr/vita-savemgr/files/1897251/logsiguess.zip)


Ah by the way, could you please add the DPAD as a control together with the touchscreen? Some people don't like to use the touchscreen that much D:

**Comment by Mapachillo** [comment]
Sorry for the late answer. How can I dump the crash?

**Comment by d3m3vilurr** [comment]
@sechstte thx.
@Mapachillo  you can find file in `ux0:data` after got a crash

and I'll check dumps if got a free time. I'm really busy sorry. :'(

**Comment by d3m3vilurr** [comment]
what use vitashell version? is that 1.9?

**Comment by sechstte** [comment]
Oh boy, i`m still on 1.82 and since I`m on 3.65 and I don't have the Molecular Shell anymore.

Now that you're saying it, it's probably an issue because I don't have the 1.9...

I'll find a way to update to 1.9 without the Molecular Shell (and the Vitashell since it's not auto-updating for some reason...) and report if I still get any errors.

Sorry for taking your time D:

**Comment by d3m3vilurr** [comment]
https://github.com/TheOfficialFloW/VitaShell/releases/tag/1.83 follow that. install 1.83 then open vitashell  & wait, will get update popup

**Comment by d3m3vilurr** [comment]
also I'll add the module into vitashell packges, current way can make the problem in the future.

**Comment by sechstte** [comment]
Works perfectly now, thanks for helping me with updating!
