### ISSUE TITLE
Could not copy directory

### ISSUE THREAD

**Issue by dustluv** [d3m3vilurr/vita-savemgr#81]
On a couple games I cannot restore the save. I get the error "Could not copy to directory". So far I'ts Mind 0 and Trails of Cold Steel.

**Comment by d3m3vilurr** [comment]
can you share you backup save?
upload here or send email(d3m3vilurr at gmail.com)

**Comment by starglad** [comment]
that was happening to me..
1-what exactly happened: I tried to transfer save games with qcma but the transfer broke my games(I couldnt even open the bubble) and I was trying to use the vpk without knowing it broke my games.
2- what i've done to fix: I reinstalled my games and kept the save folders(idk why these save folders that i'd transfered through qcma got deleted when I deleted the games, so I just transfered my games back again and started one of them..besides that I also refreshed database through vitashell, so I dont know which action really fixed it.
3- When I was having this issue the saving slots were all messed up with a lot of numbers and letters on vita save manager instead of "empty", after action 2 I got it all fixed

**Comment by EmuAGR** [comment]
This also happens to me. I can't backup.

**Comment by d3m3vilurr** [comment]
if you use 3.67 or 3.68, just reinstall latest nightly.
these versions require newer vitashell kernel plugin.

**Comment by prajwallimbu2** [comment]
Hey d3m3vilurr I on fw 3.65 on h-encore hack what my problem is when I try to backup savesdata My games get corrupted

**Comment by prajwallimbu2** [comment]
I already install the latest savemanager but when i try to backup savedata my game corrupt.

**Comment by d3m3vilurr** [comment]
@prajwallimbu2 well, is all games getting corruption? can you share your save data?

**Comment by EmuAGR** [comment]
@d3m3vilurr I was using the latest nightly from July 1st. I don't see new commits since April.

**Comment by d3m3vilurr** [comment]
@EmuAGR CI will automatically rebuild kernel plugin module. btw I'll recheck problem with last nightly

**Comment by AnalogMan151** [comment]
Getting this as well. "Could not copy directory" when attempting to back up a save. This is a fresh install of Save Manager, my savemgr folder is empty. When I am choosing a slot it looks like it's supposed to be a date but the date is way off. Example, the top slot reads `33325-06-26 17:07:01` and all the other slots read `32596-09-29 20:33:32` as of the time of this post.
