### ISSUE TITLE
Saves rapidly changing

### ISSUE THREAD

**Issue by SpooksMcBoners** [d3m3vilurr/vita-savemgr#93]
In trying to backup some of my saves but this weird issue is happening.
https://prnt.sc/n47ada I've tried reinstalling but nothing fixed it. Please help

**Comment by Originalimoc** [comment]
Same here

**Comment by Originalimoc** [comment]
Use 2.0.0 stable release, NIGHTLY is in problem.

**Comment by d3m3vilurr** [comment]
what is your vita version?

**Comment by Originalimoc** [comment]
1000 3.60 Henkaku w/ enso, SD2Vita mounted at ux0.

Nice profile image BTW XD.

**Comment by Penty2** [comment]
same problem

**Comment by d-rez** [comment]
This is because of the new implementation of storage location that was done in #60 

Just fix your config.ini that's at ux0:/data/savemgr to have the full path instead of a relative path, i.e. make sure the "base" line says the following instead of just `/data/savegames`:

`base = ux0:/data/savegames`

Everything works fine afterwards
